import Head from 'next/head'
import { Feed } from '../components/Feed'
import { Sidebar } from '../components/Sidebar'
// import { useDark } from '../hooks/useDark'

export default function Home() {
  // const [theme, toggle] = useDark()
  // console.log(theme);
  return (
    <div className='dark text-black dark:text-white'>
      <Head>
        <title>cherry blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar></Sidebar>
        <Feed></Feed>
      </main>
    </div>
  )
}

export async function getServerSideProps(){
  
}
