import Head from 'next/head'
import { Feed } from '../components/Feed'
import { Sidebar } from '../components/Sidebar'
import { getProviders, getSession } from 'next-auth/react';
import Login from '../components/Login';
import { session } from '../config/session';
import Modal from '../components/Modal';
import { useRecoilState } from 'recoil';
import { modalState } from '../atoms/midalAtom';
import Widgets from '../components/Widgets';
// import axios from 'axios';
// import { useDark } from '../hooks/useDark'
export default function Home({ trendingResults,
  followResults, providers }: any) {
  // const {data:Session} = useSession()
  const [isOpen,] = useRecoilState(modalState);
  if (!session) return <Login providers={providers} />
  return (
    <div className='dark text-black dark:text-white'>
      <Head>
        <title>cherry blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar></Sidebar>
        <Feed></Feed>
        <Widgets trendingResults={trendingResults} followResults={followResults}></Widgets>
        {isOpen && <Modal />}
      </main>
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const res1 = [
    {
      "heading": "T20 World Cup 2021 · LIVE",
      "description": "NZvAUS: New Zealand and Australia clash in the T20 World Cup final",
      "img": "https://img1.baidu.com/it/u=592570905,1313515675&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1667235600&t=c35915a8d34897267688ebc08bcf8c4c",
      "tags": [
        "#T20WorldCupFinal, ",
        "Kane Williamson"
      ]
    },
    {
      "heading": "Trending in United Arab Emirates",
      "description": "#earthquake",
      "img": "https://img1.baidu.com/it/u=592570905,1313515675&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1667235600&t=c35915a8d34897267688ebc08bcf8c4c",
      "tags": [
        "#DubaiAirshow, ",
        "#gessdubai"
      ]
    },
    {
      "heading": "Trending in Digital Creators",
      "description": "tubbo and quackity",
      "img": "",
      "tags": [
        "QUACKITY AND TUBBO,"
      ]
    }
  ]
  const trendingResults = res1
  const res2 = [
    {
      "userImg": "https://img1.baidu.com/it/u=592570905,1313515675&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1667235600&t=c35915a8d34897267688ebc08bcf8c4c",
      "username": "SpaceX",
      "tag": "@SpaceX"
    },
    {
      "userImg": "https://img1.baidu.com/it/u=592570905,1313515675&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1667235600&t=c35915a8d34897267688ebc08bcf8c4c",
      "username": "Elon Musk",
      "tag": "@elonmusk"
    },
    {
      "userImg": "https://img1.baidu.com/it/u=592570905,1313515675&fm=253&app=138&size=w931&n=0&f=JPEG&fmt=auto?sec=1667235600&t=c35915a8d34897267688ebc08bcf8c4c",
      "username": "Tesla",
      "tag": "@Tesla"
    }
  ]
  const followResults = res2
  const providers = await getProviders();
  // const session = await getSession(context)
  return {
    props: {
      trendingResults,
      followResults,
      // providers,
      // session,
    },
  };
}
